spring:
  application:
    name: alinesno-cloud-vision-stream-collector
  kafka:
    producer:
      properties:
        max.request.size: 2097152
      retries: 1
      acks: all
      batch-size: 20971520
      compression-type: gzip
    bootstrap-servers:
    - localhost:9092

server:
  port: 8081

logging:
  level:
    com.alinesno.cloud.vision.stream.controller: debug

camera:
  id:
  - demo-video
  urls:
  - ../sample-video/sample.mp4
