spring:
  application:
    name: alinesno-cloud-vision-stream-processor
  kafka:
    listener:
      concurrency: 50
    consumer:
      group-id: 1
      auto-offset-reset: earliest
      fetch-min-size: 2097152
      max-poll-records: 500
    bootstrap-servers:
    - localhost:9092

logging:
  level:
    com.alinesno.cloud.vision.stream.processor: debug